### ISSUE TITLE
Export file is empty

### ISSUE THREAD

**Issue by arntracks** [Labelbox/Labelbox#22]
After finishing labeling 8 images on a Image Classification project, I downloaded the export file but the 
file was empty. CSV or JSON are empty. Please help.
https://app.labelbox.io/projects/cjddoh40e9gq10176a12o044k/settings/interface

**Comment by casainfinita** [comment]
@arntracks  sorry about that -- we are investigating the issue.

**Comment by casainfinita** [comment]
HI @arntracks, Currently we don't auto update the project dashboard screen when new labels are made. It looks like you  created 8 labels and immediately pressed `Generate Export` without refreshing the project screen. Try generating export again after refreshing the project screen and make sure you check the title: `Export (8 labels)`. We are going to fix the underlying issue that caused this so that the project will auto update and populate with newly created labels.
