### ISSUE TITLE
unexpected keyword argument 'xy_coords'  with labelbox2pascal script

### ISSUE THREAD

**Issue by fera0013** [Labelbox/Labelbox#36]
I have exported my labeled dataset to the following json file:

[Labelbox.io_TransferLearningTest_XY.json.zip](https://github.com/Labelbox/Labelbox/files/1845415/Labelbox.io_TransferLearningTest_XY.json.zip)

When I try to convert that to the pascal voc format using the script 

```
# import labelbox2pascal library
import labelbox2pascal as lb2pa

# set labeled_data to the file path of the Labelbox JSON export
labeled_data = 'test-fixtures/Labelbox.io_TransferLearningTest_WKN.json'

# set ann_output_dir to the file path of the directory to write Pascal VOC
# annotation files. The directory must exist.
ann_output_dir = './Annotations'

# set images_output_dir to the file path of the directory to write images.
# The directory must exist.
images_output_dir = './Images'

# call the Labelbox to Pascal conversion
# NOTE: make sure to specify the correct label_format based on the export
#  format chosen on Labelbox; 'WKT' or 'XY'.
lb2pa.from_json(labeled_data=labeled_data, ann_output_dir=ann_output_dir,
                images_output_dir=images_output_dir, label_format='WKT')
```

I get the following error: 

> TypeError
>   Message=addObject() got an unexpected keyword argument 'xy_coords'
>   StackTrace:
> __init__.py:104 in add_pascal_object_from_wkt

**Comment by Riegerb** [comment]
I think this is due to having the wrong version of the Pascal VOC writer. I have updated the requirements.txt file to specify the commit that is compatible (instead of branch head).

Try this to fix your issue:
1. Pull the latest from master. `git pull`
2. Cd back into `./scripts`, activate the virtualenv and update packages with pip `pip install -r requirements.txt`

Try running your script again. I was able to convert your sample file to Pascal VOC.
