### ISSUE TITLE
Text classification, content instead of URL

### ISSUE THREAD

**Issue by ksmirenko** [Labelbox/Labelbox#50]
Hi. First of all, thank you for this great tool. I would like to use it to classify a dataset of pieces of software code (short, but multi-line). However, I haven't managed to get Labelbox (text classification template) to show the content, not URL to the file, in the labelling interface. I tried both uploading files from my computer, and uploading a CSV file with links to publicly stored files.

Is there an easy way to do it?

**Comment by manuaero** [comment]
@ksmirenko, you could create a CSV file with a column containing the actual text and import that into Labelbox. What's your user ID? We have a prototype template that might be useful otherwise -- can add it to your account.

**Comment by ksmirenko** [comment]
@manuaero I use this GitHub account to log in, not sure what my user ID is. "Kirill Smirenko" is displayed in the top-right corner.

**Comment by danielrasmuson** [comment]
Hi @ksmirenko 

Templates are just basic html and css so if they don't do what you need you can always customize it.

Here is a quick template to classify code.

<img width="518" alt="screen shot 2018-04-11 at 11 53 40 am" src="https://user-images.githubusercontent.com/4013767/38637211-4f6052e8-3d7f-11e8-8a81-71bc6a01d2fe.png">

```html
<script src="https://api.labelbox.io/client/v0.1/labeling-api.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.3.3/ace.js"></script>
<style type="text/css" media="screen">
  #editor { 
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    width: 500px;
    height: 500px;
  }
</style>

<div style="width: 500px; height: 500px;">
  <div id="editor"></div>  
</div>
<div style="display: flex;">
  <button onclick="label('bad')">Bad Quality</button>
  <button onclick="label('good')">Good Quality</button>
</div>
    
<script>
var editor = ace.edit("editor");
editor.setTheme("ace/theme/monokai");
editor.session.setMode("ace/mode/javascript");

function label(label){
  Labelbox.setLabelForAsset(label).then(() => {
    Labelbox.fetchNextAssetToLabel();
  });
}

Labelbox.currentAsset().subscribe((asset) => {
  if (asset){
    // TODO uncomment this line to remove hardcoded line once you've enabled CORS
    // const urlToCode = data.asset;
    const urlToCode = "https://storage.googleapis.com/audio-example/App.tsx";
    fetch(urlToCode).then((res) => res.text())
      .then((code) => {
        editor.setValue(code);
      });
  }
})
</script>
```

Make sure the URL to your code is CORS enabled otherwise the browser won't be able to read the data from the that url. If you store your data on google cloud here is how you can enable CORS for a bucket, https://developer.bitmovin.com/hc/en-us/articles/360000059353-How-do-I-set-up-CORS-for-my-Google-Cloud-Storage-Bucket-.

Let me know if you have any questions.

**Comment by danielrasmuson** [comment]
Hi @ksmirenko, let me know if you have any questions or if I can help further.
